#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Gallery-Remote
version:      0.2
version_from: Remote.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
